### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by coleweinman** [EngineersMods/EngineersWorkshop#39]
###### **Forge Version & Engineer's Workshop Version [MAKE SURE YOU ARE RUNNING THE LATEST BUILD]**
EngineersWorkshop-1.3.5-1.10.2.jar

###### **Expected behavior**
Server to not crash

###### **Actual Behavior**
Server crashes

###### **Link to Crashlog or Forgelog** *[If Applicable]*
https://pastebin.com/e3r9cZsV

###### **Steps to reproduce** *[If Applicable]*
Not really sure, I have a empty workbench placed down for a while and all of a sudden it crashed the server like a day later so idk.

**Comment by JorVaCoding** [comment]
This is an issue with the config. The config allowed the minimum solar generation to be 0 (in your case this is 0). And if there was rain, it would slow down the rf production by that config number. Since it was 0, the weather modifier was 0 and caused a divide by 0 crash. I've change the minimum configable amount to be 1. 

Note: **IF YOU WANT TO STOP SOLAR UPGRADES FROM BEING USABLE, DISABLE THE UPGRADE IN THE CONFIG, DO NOT CHANGE PRODUCTION TO 0.**
